valid_channels = {
    "mien-bac":         "Miền bắc",
    "an-giang":         "An Giang",
    "bac-lieu":         "Bạc Liêu",
    "ben-tre":          "Bến Tre",
    "binh-dinh":        "Bình Định",
    "binh-duong":       "Bình Dương",
    "binh-phuoc":       "Bình Phước",
    "binh-thuan":       "Bình Thuận",
    "ca-mau":           "Cà Mau",
    "can-tho":          "Cần Thơ",
    "da-lat":           "Đà Lạt",
    "da-nang":          "Đà Nẵng",
    "dak-lak":          "Đắk Lắk",
    "dak-nong":         "Đắk Nông",
    "dong-nai":         "Đồng Nai",
    "dong-thap":        "Đồng Tháp",
    "gia-lai":          "Gia Lai",
    "hau-giang":        "Hậu Giang",
    "khanh-hoa":        "Khánh Hòa",
    "kien-giang":       "Kiên Giang",
    "kon-tum":          "Kon Tum",
    "long-an":          "Long An",
    "ninh-thuan":       "Ninh Thuận",
    "phu-yen":          "Phú Yên",
    "quang-binh":       "Quảng Bình",
    "quang-nam":        "Quảng Nam",    
    "quang-ngai":       "Quảng Ngãi",
    "quang-tri":        "Quảng Trị",
    "soc-trang":        "Sóc Trăng",
    "tay-ninh":         "Tây Ninh",
    "thua-thien-hue":   "Thừa Thiên Huế",
    "tien-giang":       "Tiền Giang",
    "tp-hcm":           "TP. HCM",
    "tra-vinh":         "Trà Vinh",
    "vinh-long":        "Vĩnh Long",
    "vung-tau":         "Vũng Tàu",
} 

# https://www.minhngoc.net.vn/getkqxs//{date}.js
minh_ngoc_channel_urls = {
    "mien-bac":         "https://www.minhngoc.net.vn/getkqxs/mien-bac/{date}.js",
    "an-giang":         "https://www.minhngoc.net.vn/getkqxs/an-giang/{date}.js",
    "bac-lieu":         "https://www.minhngoc.net.vn/getkqxs/bac-lieu/{date}.js",
    "ben-tre":          "https://www.minhngoc.net.vn/getkqxs/ben-tre/{date}.js",
    "binh-dinh":        "https://www.minhngoc.net.vn/getkqxs/binh-dinh/{date}.js",
    "binh-duong":       "https://www.minhngoc.net.vn/getkqxs/binh-duong/{date}.js",
    "binh-phuoc":       "https://www.minhngoc.net.vn/getkqxs/binh-phuoc/{date}.js",
    "binh-thuan":       "https://www.minhngoc.net.vn/getkqxs/binh-thuan/{date}.js",
    "ca-mau":           "https://www.minhngoc.net.vn/getkqxs/ca-mau/{date}.js",
    "can-tho":          "https://www.minhngoc.net.vn/getkqxs/can-tho/{date}.js",
    "da-lat":           "https://www.minhngoc.net.vn/getkqxs/da-lat/{date}.js",
    "da-nang":          "https://www.minhngoc.net.vn/getkqxs/da-nang/{date}.js",
    "dak-lak":          "https://www.minhngoc.net.vn/getkqxs/dak-lak/{date}.js",
    "dak-nong":         "https://www.minhngoc.net.vn/getkqxs/dak-nong/{date}.js",
    "dong-nai":         "https://www.minhngoc.net.vn/getkqxs/dong-nai/{date}.js",
    "dong-thap":        "https://www.minhngoc.net.vn/getkqxs/dong-thap/{date}.js",
    "gia-lai":          "https://www.minhngoc.net.vn/getkqxs/gia-lai/{date}.js",
    "hau-giang":        "https://www.minhngoc.net.vn/getkqxs/hau-giang/{date}.js",
    "khanh-hoa":        "https://www.minhngoc.net.vn/getkqxs/khanh-hoa/{date}.js",
    "kien-giang":       "https://www.minhngoc.net.vn/getkqxs/kien-giang/{date}.js",
    "kon-tum":          "https://www.minhngoc.net.vn/getkqxs/kon-tum/{date}.js",
    "long-an":          "https://www.minhngoc.net.vn/getkqxs/long-an/{date}.js",
    "ninh-thuan":       "https://www.minhngoc.net.vn/getkqxs/ninh-thuan/{date}.js",
    "phu-yen":          "https://www.minhngoc.net.vn/getkqxs/phu-yen/{date}.js",
    "quang-binh":       "https://www.minhngoc.net.vn/getkqxs/quang-binh/{date}.js",
    "quang-nam":        "https://www.minhngoc.net.vn/getkqxs/quang-nam/{date}.js",
    "quang-ngai":       "https://www.minhngoc.net.vn/getkqxs/quang-ngai/{date}.js",
    "quang-tri":        "https://www.minhngoc.net.vn/getkqxs/quang-tri/{date}.js",
    "soc-trang":        "https://www.minhngoc.net.vn/getkqxs/soc-trang/{date}.js",
    "tay-ninh":         "https://www.minhngoc.net.vn/getkqxs/tay-ninh/{date}.js",
    "thua-thien-hue":   "https://www.minhngoc.net.vn/getkqxs/thua-thien-hue/{date}.js",
    "tien-giang":       "https://www.minhngoc.net.vn/getkqxs/tien-giang/{date}.js",
    "tp-hcm":           "https://www.minhngoc.net.vn/getkqxs/tp-hcm/{date}.js",
    "tra-vinh":         "https://www.minhngoc.net.vn/getkqxs/tra-vinh/{date}.js",
    "vinh-long":        "https://www.minhngoc.net.vn/getkqxs/vinh-long/{date}.js",
    "vung-tau":         "https://www.minhngoc.net.vn/getkqxs/vung-tau/{date}.js",
}

# https://www.kqxs.vn/
kqxs_channel_urls = {
    "mien-bac":         "https://www.kqxs.vn/mien-bac?date={date}",
    "ho-chi-minh":      "https://www.kqxs.vn/mien-nam/xo-so-ho-chi-minh?date={date}",
    "dong-thap":        "https://www.kqxs.vn/mien-nam/xo-so-dong-thap?date={date}",
    "ca-mau":           "https://www.kqxs.vn/mien-nam/xo-so-ca-mau?date={date}",
    "ben-tre":          "https://www.kqxs.vn/mien-nam/xo-so-ben-tre?date={date}",
    "vung-tau":         "https://www.kqxs.vn/mien-nam/xo-so-vung-tau?date={date}",
    "bac-lieu":         "https://www.kqxs.vn/mien-nam/xo-so-bac-lieu?date={date}",
    "dong-nai":         "https://www.kqxs.vn/mien-nam/xo-so-dong-nai?date={date}",
    "can-tho":          "https://www.kqxs.vn/mien-nam/xo-so-can-tho?date={date}",
    "soc-trang":        "https://www.kqxs.vn/mien-nam/xo-so-soc-trang?date={date}",
    "tay-ninh":         "https://www.kqxs.vn/mien-nam/xo-so-tay-ninh?date={date}",
    "an-giang":         "https://www.kqxs.vn/mien-nam/xo-so-an-giang?date={date}",
    "binh-thuan":       "https://www.kqxs.vn/mien-nam/xo-so-binh-thuan?date={date}",
    "vinh-long":        "https://www.kqxs.vn/mien-nam/xo-so-vinh-long?date={date}",
    "binh-duong":       "https://www.kqxs.vn/mien-nam/xo-so-binh-duong?date={date}",
    "tra-vinh":         "https://www.kqxs.vn/mien-nam/xo-so-tra-vinh?date={date}",
    "long-an":          "https://www.kqxs.vn/mien-nam/xo-so-long-an?date={date}",
    "binh-phuoc":       "https://www.kqxs.vn/mien-nam/xo-so-binh-phuoc?date={date}",
    "hau-giang":        "https://www.kqxs.vn/mien-nam/xo-so-hau-giang?date={date}",
    "tien-giang":       "https://www.kqxs.vn/mien-nam/xo-so-tien-giang?date={date}",
    "kien-giang":       "https://www.kqxs.vn/mien-nam/xo-so-kien-giang?date={date}",
    "da-lat":           "https://www.kqxs.vn/mien-nam/xo-so-da-lat?date={date}",
    "phu-yen":          "https://www.kqxs.vn/mien-trung/xo-so-phu-yen?date={date}",
    "thua-thien-hue":   "https://www.kqxs.vn/mien-trung/xo-so-thua-thien-hue?date={date}",
    "dac-lac":          "https://www.kqxs.vn/mien-trung/xo-so-dac-lac?date={date}",
    "quang-nam":        "https://www.kqxs.vn/mien-trung/xo-so-quang-nam?date={date}",
    "da-nang":          "https://www.kqxs.vn/mien-trung/xo-so-da-nang?date={date}",
    "khanh-hoa":        "https://www.kqxs.vn/mien-trung/xo-so-khanh-hoa?date={date}",
    "quang-binh":       "https://www.kqxs.vn/mien-trung/xo-so-quang-binh?date={date}",
    "binh-dinh":        "https://www.kqxs.vn/mien-trung/xo-so-binh-dinh?date={date}",
    "quang-tri":        "https://www.kqxs.vn/mien-trung/xo-so-quang-tri?date={date}",
    "gia-lai":          "https://www.kqxs.vn/mien-trung/xo-so-gia-lai?date={date}",
    "ninh-thuan":       "https://www.kqxs.vn/mien-trung/xo-so-ninh-thuan?date={date}",
    "quang-ngai":       "https://www.kqxs.vn/mien-trung/xo-so-quang-ngai?date={date}",
    "dac-nong":         "https://www.kqxs.vn/mien-trung/xo-so-dac-nong?date={date}",
    "kon-tum":          "https://www.kqxs.vn/mien-trung/xo-so-kon-tum?date={date}",
}

# https://xskt.com.vn
xskt_channel_urls = {
    "mien-bac":          "https://xskt.com.vn/xsmb/ngay-{date}",
    "tp-hcm":            "https://xskt.com.vn/xshcm-xstp/ngay-{date}",
    "an-giang":          "https://xskt.com.vn/xsag/ngay-{date}",
    "binh-duong":        "https://xskt.com.vn/xsbd/ngay-{date}",
    "bac-lieu":          "https://xskt.com.vn/xsbl/ngay-{date}",
    "binh-phuoc":        "https://xskt.com.vn/xsbp/ngay-{date}",
    "ben-tre":           "https://xskt.com.vn/xsbt/ngay-{date}",
    "binh-thuan":        "https://xskt.com.vn/xsbth/ngay-{date}",
    "ca-mau":            "https://xskt.com.vn/xscm/ngay-{date}",
    "can-tho":           "https://xskt.com.vn/xsct/ngay-{date}",
    "da-lat":            "https://xskt.com.vn/xsld-xsdl/ngay-{date}",
    "dong-nai":          "https://xskt.com.vn/xsdn/ngay-{date}",
    "dong-thap":         "https://xskt.com.vn/xsdt/ngay-{date}",
    "hau-giang":         "https://xskt.com.vn/xshg/ngay-{date}",
    "kien-giang":        "https://xskt.com.vn/xskg/ngay-{date}",
    "long-an":           "https://xskt.com.vn/xsla/ngay-{date}",
    "soc-trang":         "https://xskt.com.vn/xsst/ngay-{date}",
    "tien-giang":        "https://xskt.com.vn/xstg/ngay-{date}",
    "tay-ninh":          "https://xskt.com.vn/xstn/ngay-{date}",
    "tra-vinh":          "https://xskt.com.vn/xstv/ngay-{date}",
    "vinh-long":         "https://xskt.com.vn/xsvl/ngay-{date}",
    "vung-tau":          "https://xskt.com.vn/xsvt/ngay-{date}",
    "binh-dinh":         "https://xskt.com.vn/xsbdi/ngay-{date}",
    "dak-lak":           "https://xskt.com.vn/xsdlk/ngay-{date}",
    "da-nang":           "https://xskt.com.vn/xsdng-xsdna/ngay-{date}",
    "dak-nong":          "https://xskt.com.vn/xsdno/ngay-{date}",
    "gia-lai":           "https://xskt.com.vn/xsgl/ngay-{date}",
    "khanh-hoa":         "https://xskt.com.vn/xskh/ngay-{date}",
    "kon-tum":           "https://xskt.com.vn/xskt/ngay-{date}",
    "ninh-thuan":        "https://xskt.com.vn/xsnt/ngay-{date}",
    "phu-yen":           "https://xskt.com.vn/xspy/ngay-{date}",
    "quang-binh":        "https://xskt.com.vn/xsqb/ngay-{date}",
    "quang-ngai":        "https://xskt.com.vn/xsqng/ngay-{date}",
    "quang-nam":         "https://xskt.com.vn/xsqnm-xsqna/ngay-{date}",
    "quang-tri":         "https://xskt.com.vn/xsqt/ngay-{date}",
    "thua-thien-hue":    "https://xskt.com.vn/xstth/ngay-{date}",
}