version: "3.8"

services:
  mongodb:
    image: mongo:8.0.1
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - database_net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=""
      # - ME_CONFIG_BASICAUTH_PASSWORD=""
    networks:
      - database_net
    depends_on:
      - mongodb

networks:
  database_net:
