version: "3.8"

services:
  api:
    build: .
    container_name: worker-lottery
    ports:
      - 8801:8801
    environment:
      - MONGO_URI='mongodb://database:27017/'
    networks:
      - database_net
    depends_on:
      - database

networks:
  database_net:
